### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by slawiko** [ChesnAnastasia/Project1#5]
@ChesnAnastasia 

### profile
- мистическая функция. `b1`, `b2`, `b3` ,... - плохое наименование

Я не нашел index.html (если смотреть по тэгу `task5`), который можно было бы запустить и проверить эту лабораторную.

**Comment by ChesnAnastasia** [comment]
Ну с кнопками b1 и т.д. да, не очень вышло, а index.html должен был быть

**Comment by ChesnAnastasia** [comment]
Я посмотрела, короче я тогда не знала, как вы проверяете и закинула в новую папку, а путь не прописала. Если скачать по тегу task5, то там dom.js надо закинуть в папку task3. Извините, что-то я там херню сделала

**Comment by ChesnAnastasia** [comment]
@slawiko 
Я посмотрела, короче я тогда не знала, как вы проверяете и закинула в новую папку, а путь не прописала. Если скачать по тегу task5, то там dom.js надо закинуть в папку task3. Извините, что-то я там херню сделала

**Comment by ChesnAnastasia** [comment]
И index.js(в task4 находится) вроде тоже надо в папку task3

**Comment by slawiko** [comment]
@ChesnAnastasia 

да, так заработало

### Общие
- ставить фигурные скобки вокруг тела `if` или `while` даже с одним выражением всё равно нужно.
- тип переменных var относится к старым стандартам EcmaScript. Следует использовать более новые типы переменных: `let` (для изменяемых данных) и `const` (для неизменяемых). Предпочтительнее использовать `const`. Но ни в коем случае не перемешивайте их с `var`.

В целом неплохо
